"""Shared typed primitives for ``xrtoolz``.

These types are deliberately agnostic of any particular submodule
(``data``, ``geo``, ``ocn``, ``atm``, ...). They exist so every module
speaks the same language for things like "a lon/lat bounding box",
"a time window", "a CF variable".

Exports:

- Spatial: :class:`BBox`.
- Temporal: :class:`TimeRange`.
- Vertical: :class:`DepthRange`, :class:`PressureLevels`.
- Request: :class:`Request` (typed composition of the above).
- Variables: :class:`Variable`, :data:`REGISTRY`, :func:`resolve`,
  :func:`register`.
- Validation: :func:`validate_variable`, :func:`validate_dataset`,
  :func:`apply_cf_attrs`, :class:`ValidationReport`, :class:`Issue`,
  :class:`Severity`.
"""

from xrtoolz.types._src.geometry import BBox
from xrtoolz.types._src.levels import DepthRange, PressureLevels
from xrtoolz.types._src.request import Request
from xrtoolz.types._src.station import Station, StationCollection
from xrtoolz.types._src.time import TimeRange
from xrtoolz.types._src.validation import (
    Issue,
    Severity,
    ValidationReport,
    apply_cf_attrs,
    validate_dataset,
    validate_variable,
)
from xrtoolz.types._src.variable import (
    ADT,
    AIR_TEMPERATURE,
    AIR_TEMPERATURE_DAILY_MAX,
    AIR_TEMPERATURE_DAILY_MEAN,
    AIR_TEMPERATURE_DAILY_MIN,
    AIR_TEMPERATURE_MAX,
    AIR_TEMPERATURE_MIN,
    ANALYSED_SST,
    BBP443,
    CHL,
    D2M,
    DENS,
    DEW_POINT_TEMPERATURE,
    DOWNWARD_LONGWAVE_RADIATION,
    DOWNWARD_SHORTWAVE_RADIATION,
    FRESH_SNOW,
    ICE_CONC,
    KD490,
    MDT,
    MEAN_SEA_LEVEL_PRESSURE_HPA,
    MSL,
    NO3,
    O2,
    PH,
    PHYC,
    PO4,
    PP,
    PRECIPITATION_AMOUNT,
    REGISTRY,
    RELATIVE_HUMIDITY,
    RRS412,
    RRS443,
    RRS490,
    RRS510,
    RRS555,
    RRS670,
    SEA_LEVEL_PRESSURE,
    SEA_SURFACE_SALINITY,
    SEA_SURFACE_TEMPERATURE_INSITU,
    SI,
    SLA,
    SNOW_WATER_EQUIVALENT,
    SO,
    SOIL_TEMPERATURE_5CM,
    SOIL_TEMPERATURE_20CM,
    SOS,
    SP,
    SPCO2,
    SPM,
    SSH,
    SSRD,
    SST,
    SST_OBS,
    SUNSHINE_DURATION,
    SUNSHINE_DURATION_DAILY,
    SURFACE_PRESSURE_HPA,
    SURFACE_PRESSURE_MAX_HPA,
    SURFACE_PRESSURE_MIN_HPA,
    SURFACE_SNOW_THICKNESS,
    T2M,
    TOTAL_CLOUD_COVER,
    TP,
    U10,
    UGOS,
    UO,
    V10,
    VGOS,
    VISIBILITY,
    VO,
    WATER_VAPOUR_PRESSURE,
    WAVE_FROM_DIRECTION,
    WAVE_PERIOD,
    WAVE_SIGNIFICANT_HEIGHT,
    WIND_FROM_DIRECTION,
    WIND_FROM_DIRECTION_DAILY,
    WIND_FROM_DIRECTION_OF_GUST,
    WIND_SPEED,
    WIND_SPEED_DAILY_MEAN,
    WIND_SPEED_OF_GUST,
    WIND_SPEED_OF_GUST_DAILY,
    ZOOC,
    ZSD,
    Variable,
    register,
    resolve,
)


__all__ = [
    "ADT",
    "AIR_TEMPERATURE",
    "AIR_TEMPERATURE_DAILY_MAX",
    "AIR_TEMPERATURE_DAILY_MEAN",
    "AIR_TEMPERATURE_DAILY_MIN",
    "AIR_TEMPERATURE_MAX",
    "AIR_TEMPERATURE_MIN",
    "ANALYSED_SST",
    "BBP443",
    "CHL",
    "D2M",
    "DENS",
    "DEW_POINT_TEMPERATURE",
    "DOWNWARD_LONGWAVE_RADIATION",
    "DOWNWARD_SHORTWAVE_RADIATION",
    "FRESH_SNOW",
    "ICE_CONC",
    "KD490",
    "MDT",
    "MEAN_SEA_LEVEL_PRESSURE_HPA",
    "MSL",
    "NO3",
    "O2",
    "PH",
    "PHYC",
    "PO4",
    "PP",
    "PRECIPITATION_AMOUNT",
    "REGISTRY",
    "RELATIVE_HUMIDITY",
    "RRS412",
    "RRS443",
    "RRS490",
    "RRS510",
    "RRS555",
    "RRS670",
    "SEA_LEVEL_PRESSURE",
    "SEA_SURFACE_SALINITY",
    "SEA_SURFACE_TEMPERATURE_INSITU",
    "SI",
    "SLA",
    "SNOW_WATER_EQUIVALENT",
    "SO",
    "SOIL_TEMPERATURE_5CM",
    "SOIL_TEMPERATURE_20CM",
    "SOS",
    "SP",
    "SPCO2",
    "SPM",
    "SSH",
    "SSRD",
    "SST",
    "SST_OBS",
    "SUNSHINE_DURATION",
    "SUNSHINE_DURATION_DAILY",
    "SURFACE_PRESSURE_HPA",
    "SURFACE_PRESSURE_MAX_HPA",
    "SURFACE_PRESSURE_MIN_HPA",
    "SURFACE_SNOW_THICKNESS",
    "T2M",
    "TOTAL_CLOUD_COVER",
    "TP",
    "U10",
    "UGOS",
    "UO",
    "V10",
    "VGOS",
    "VISIBILITY",
    "VO",
    "WATER_VAPOUR_PRESSURE",
    "WAVE_FROM_DIRECTION",
    "WAVE_PERIOD",
    "WAVE_SIGNIFICANT_HEIGHT",
    "WIND_FROM_DIRECTION",
    "WIND_FROM_DIRECTION_DAILY",
    "WIND_FROM_DIRECTION_OF_GUST",
    "WIND_SPEED",
    "WIND_SPEED_DAILY_MEAN",
    "WIND_SPEED_OF_GUST",
    "WIND_SPEED_OF_GUST_DAILY",
    "ZOOC",
    "ZSD",
    "BBox",
    "DepthRange",
    "Issue",
    "PressureLevels",
    "Request",
    "Severity",
    "Station",
    "StationCollection",
    "TimeRange",
    "ValidationReport",
    "Variable",
    "apply_cf_attrs",
    "register",
    "resolve",
    "validate_dataset",
    "validate_variable",
]
